version: 0.0
Resources:
  - TargetService:
      Type: AWS::EKS::Service
      Properties:
        ClusterName: brain-task-cluster
        Namespace: default
        TaskDefinition: brain-task-app
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: root

